### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by jaredbidlow** [rossshannon/pincushion#1]
I know that pinboard was down yesterday, Bookmarklet still isn't working. "cross-domain request failed"

**Comment by rossshannon** [comment]
Thanks for the report. The whole Pinboard site went down briefly yesterday due to a DDOS attack, but the API, as well as full-text search, did not come back for a number of hours, as they were on a separate server. Maciej posted about this on [the blog](https://blog.pinboard.in/2015/02/api_outage/) and [Pinboard’s twitter account](https://twitter.com/pinboard) live-tweeted the incident.

This disabled all third-party apps that use the API to post bookmarks. To Pincushion, it looked like the Ajax call it uses to pull data in from the Pinboard API was failing.

If a similar event happens in future, the quickest solution is to use the standard [Pinboard bookmarklet](https://pinboard.in/howto/#bookmarklets) (which doesn’t need to use the API) to allow you to continue saving bookmarks until API access is restored.
